languages:
  JavaScript: true
  PHP: true
exclude_paths:
- tests/**/*
- demo/**/*
- js/*.min.js
- js/jqueryui/**/*
- js/select2/**/*
engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false